#!/usr/bin/env python3
"""prejos — colored interactive setup wizard.

Walks you through API_ID / API_HASH / BOT_TOKEN and writes a .env file.
Run:  python setup.py
"""
from __future__ import annotations

import os
import re
import sys

try:
    from colorama import Fore, Style, init as colorama_init
except ImportError:  # graceful: still works without colour
    class _Dummy:
        def __getattr__(self, _):  # noqa: D401
            return ""

    Fore = Style = _Dummy()  # type: ignore

    def colorama_init(*_a, **_k):  # noqa: D401
        return None


colorama_init(autoreset=True)

ENV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env")

C = Fore.CYAN
G = Fore.GREEN
Y = Fore.YELLOW
R = Fore.RED
M = Fore.MAGENTA
D = Style.DIM
B = Style.BRIGHT
RESET = Style.RESET_ALL


BANNER = rf"""{M}{B}
   ___  ____ ___    _ ___  ___
  / _ \|  _ \ __|  | / _ \/ __|
 | (_) |  _ <  _|  | | (_) \__ \
  \___/|_| \_\___|_/ \___/|___/
{RESET}{C}      premium custom-emoji inspector{RESET}
"""


def hr() -> None:
    print(f"{D}{'-' * 46}{RESET}")


def prompt(label: str, *, hint: str = "", secret_tail: bool = False, validator=None, default: str = "") -> str:
    while True:
        suffix = f" {D}[{default}]{RESET}" if default else ""
        if hint:
            print(f"{D}{hint}{RESET}")
        raw = input(f"{C}{B}{label}{RESET}{suffix} {Y}>{RESET} ").strip()
        if not raw and default:
            raw = default
        if not raw:
            print(f"{R}  ! required{RESET}")
            continue
        if validator:
            err = validator(raw)
            if err:
                print(f"{R}  ! {err}{RESET}")
                continue
        shown = ("\u2026" + raw[-4:]) if secret_tail and len(raw) > 4 else raw
        print(f"{G}  ok{RESET} {D}{shown}{RESET}")
        return raw


def v_api_id(s: str) -> str | None:
    return None if s.isdigit() else "API_ID is all digits (from my.telegram.org)"


def v_api_hash(s: str) -> str | None:
    return None if re.fullmatch(r"[0-9a-fA-F]{32}", s) else "API_HASH is a 32-char hex string"


def v_token(s: str) -> str | None:
    return None if re.fullmatch(r"\d{6,}:[\w-]{30,}", s) else "BOT_TOKEN looks like 123456:ABC-..."


def read_existing() -> dict[str, str]:
    data: dict[str, str] = {}
    if os.path.exists(ENV_PATH):
        for line in open(ENV_PATH):
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, val = line.partition("=")
                data[k.strip()] = val.strip()
    return data


def write_env(values: dict[str, str]) -> None:
    lines = [
        "# prejos configuration (generated by setup.py)",
        f"API_ID={values.get('API_ID', '')}",
        f"API_HASH={values.get('API_HASH', '')}",
        f"BOT_TOKEN={values.get('BOT_TOKEN', '')}",
        f"ALLOWED_USERS={values.get('ALLOWED_USERS', '')}",
        "",
    ]
    with open(ENV_PATH, "w") as f:
        f.write("\n".join(lines))
    os.chmod(ENV_PATH, 0o600)


def main() -> None:
    print(BANNER)
    existing = read_existing()
    if existing.get("API_ID") and existing.get("BOT_TOKEN"):
        print(f"{Y}A .env already exists.{RESET}")
        if input(f"{C}Overwrite it? {D}[y/N]{RESET} {Y}>{RESET} ").strip().lower() not in ("y", "yes"):
            print(f"{D}Keeping existing config. Bye.{RESET}")
            return
    hr()
    print(f"{B}Step 1{RESET} {D}credentials from{RESET} {C}https://my.telegram.org{RESET}")
    api_id = prompt("API_ID", hint="API development tools > App api_id", validator=v_api_id,
                    default=existing.get("API_ID", ""))
    api_hash = prompt("API_HASH", hint="the 32-char App api_hash", secret_tail=True, validator=v_api_hash,
                      default=existing.get("API_HASH", ""))
    hr()
    print(f"{B}Step 2{RESET} {D}bot token from{RESET} {C}@BotFather{RESET}")
    token = prompt("BOT_TOKEN", hint="/newbot or /token in @BotFather", secret_tail=True, validator=v_token,
                   default=existing.get("BOT_TOKEN", ""))
    hr()
    print(f"{B}Step 3{RESET} {D}optional access control{RESET}")
    print(f"{D}Comma-separated user ids allowed to use the bot. Empty = everyone.{RESET}")
    allowed = input(f"{C}{B}ALLOWED_USERS{RESET} {Y}>{RESET} ").strip()

    write_env(
        {"API_ID": api_id, "API_HASH": api_hash, "BOT_TOKEN": token, "ALLOWED_USERS": allowed}
    )
    hr()
    print(f"{G}{B}\u2714 wrote {ENV_PATH}{RESET} {D}(chmod 600){RESET}")
    print(f"{C}Start the bot:{RESET}  {B}python bot.py{RESET}")


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print(f"\n{R}cancelled{RESET}")
        sys.exit(1)
